name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  Compilation:
    name: Compilation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [ gcc, clang ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        env:
          CC: ${{ matrix.compiler }}
        run:
          make all
