name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

strategy:
  matrix:
    compiler: [ gcc, clang ]

jobs:
  Compilation:
    name: Compilation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        env:
          CC: ${{ matrix.compiler }}
        run:
          make all
